# Docker Image
image: 
  name: ghcr.io/sushrut1101/docker:arch
  
services: 
  - docker:dind

# Stages
stages:
  - build

# SSH Job
ssh:
  stage: build
  timeout: 1 month
  script:
    - sudo bash tmate.sh | tee /tmp/ssh.txt
